"""empty message

Revision ID: 1af44cadf06c
Revises: 
Create Date: 2022-11-04 18:16:36.504504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af44cadf06c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Object_lab', sa.String(length=45), nullable=True),
    sa.Column('Object_div', sa.String(length=300), nullable=True),
    sa.Column('Object_compname', sa.String(length=45), nullable=True),
    sa.Column('Object_comp_processor', sa.String(length=45), nullable=True),
    sa.Column('Object_comp_RAM', sa.String(length=45), nullable=True),
    sa.Column('Object_comp_operational_system', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Object_id', sa.Integer(), nullable=False),
    sa.Column('Problem', sa.String(length=60), nullable=True),
    sa.Column('Description', sa.String(length=400), nullable=True),
    sa.Column('Status', sa.String(length=60), nullable=True),
    sa.Column('Time_created', sa.Date(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calls')
    op.drop_table('users')
    op.drop_table('object')
    # ### end Alembic commands ###
