"""empty message

Revision ID: 6fa8c6da366f
Revises: 
Create Date: 2022-09-28 22:21:55.406510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa8c6da366f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab', sa.Integer(), nullable=False),
    sa.Column('comp', sa.Integer(), nullable=False),
    sa.Column('problem', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call')
    # ### end Alembic commands ###
