"""empty message

Revision ID: cd9788f7920a
Revises: 6fa8c6da366f
Create Date: 2022-09-28 22:24:55.339511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd9788f7920a'
down_revision = '6fa8c6da366f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab', sa.Integer(), nullable=False),
    sa.Column('comp', sa.Integer(), nullable=False),
    sa.Column('problem', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('call')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lab', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('calls')
    # ### end Alembic commands ###
