"""empty message

Revision ID: e27933940846
Revises: 993ce69eb88e
Create Date: 2022-09-29 22:32:03.291971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e27933940846'
down_revision = '993ce69eb88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'time_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'time_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
